### ISSUE TITLE
How to solve the problem of blurred Chinese fonts

### ISSUE THREAD

**Issue by Charltsing** [HexaEngine/Hexa.NET.ImGui.Widgets#1]
IMGUI.net sample
![1](https://github.com/user-attachments/assets/970329db-e9ba-45ab-acc6-56ebc946a323)

Hexa.NET.ImGui.Widgets demo
![2](https://github.com/user-attachments/assets/763e1d6d-9748-4813-aec8-6c8a5c1fa270)

Maybe there is a way to make Chinese fonts not appear blurry at 16 pixels, but I haven't found it yet.

**Comment by JunaMeinhold** [comment]
You shouldn't used fixed (in this context) this will create a heap corruption, you either have to use the File load function or you have to keep the pointer alive for the time that the texture is created. And additionally read the Ownership comment, ImGui cannot free a piece of memory allocated with the GC either use mashal AllocH and Free or my utils.

**Comment by JunaMeinhold** [comment]
the pointer has to be alive until you call          
```cs 
ImGui.GetTexDataAsRGBA32(io.Fonts, &pixels, &width, &height, null);
 ```
and create a texture after that it's safe to free.

**Comment by JunaMeinhold** [comment]
if you want that imgui keeps ownership then i suggest using ImGui.MemAlloc instead of Marshal or my utils, this prevents issues with freeing.

**Comment by JunaMeinhold** [comment]
(font size 24)
![image](https://github.com/user-attachments/assets/5012583e-b420-456d-9a8a-13a87ad08bcf)
(font size 16)
![image](https://github.com/user-attachments/assets/b52a6120-c79a-433c-8582-690c2235cd69)
(font size 16 with config.PixelSnapH = true; config.OversampleH = 1;)
![image](https://github.com/user-attachments/assets/9150e9cc-7201-44c1-96ac-a26d22eb28d2)

the smaller you go, the more "blur" you get, and make sure you have your DPI configuration correct. (like in SDL2 or WinApi, or any windowing framework.)

**Comment by Charltsing** [comment]
It may be a problem with ImGui

Maybe there is a way to make Chinese fonts not appear blurry at 16 pixels, but I haven't found it yet.
