### ISSUE TITLE
Exception in OpenDialog when /dev folder's tree node icon is clicked

### ISSUE THREAD

**Issue by bparvanov** [HexaEngine/Hexa.NET.ImGui.Widgets#2]
System.UnauthorizedAccessException: Access to the path '/dev/fd/5' is denied.
 ---> System.IO.IOException: Bad file descriptor
   --- End of inner exception stack trace ---
   at System.IO.FileStatus.ThrowOnCacheInitializationError(ReadOnlySpan`1 path)
   at System.IO.FileStatus.GetAttributes(SafeFileHandle handle, ReadOnlySpan`1 path, ReadOnlySpan`1 fileName, Boolean continueOnError)
   at System.IO.FileSystemInfo.get_Attributes()
   at System.IO.FileSystem.GetAttributes(String fullPath)
   at Hexa.NET.ImGui.Widgets.Dialogs.FileSystemHelper.GetFileSystemEntries(String folder, RefreshFlags refreshFlags, List`1 allowedExtensions) in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/Dialogs/FileSystemHelper.cs:line 243
   at Hexa.NET.ImGui.Widgets.ImGuiFileTreeView.<FileTreeView>g__Display|0_0(FileSystemItem item, String& currentFolder, Boolean first) in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/ImGuiFileTreeView.cs:line 34
   at Hexa.NET.ImGui.Widgets.ImGuiFileTreeView.<FileTreeView>g__Display|0_0(FileSystemItem item, String& currentFolder, Boolean first) in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/ImGuiFileTreeView.cs:line 37
   at Hexa.NET.ImGui.Widgets.ImGuiFileTreeView.FileTreeView(String strId, Vector2 size, String& currentFolder, String homeFolder) in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/ImGuiFileTreeView.cs:line 80
   at Hexa.NET.ImGui.Widgets.Dialogs.FileDialogBase.SidePanel() in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/Dialogs/FileDialogBase.cs:line 502
   at Hexa.NET.ImGui.Widgets.Dialogs.FileDialogBase.DrawExplorer() in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/Dialogs/FileDialogBase.cs:line 419
   at Hexa.NET.ImGui.Widgets.Dialogs.OpenFileDialog.DrawContent() in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/Dialogs/OpenFileDialog.cs:line 94
   at Hexa.NET.ImGui.Widgets.Dialogs.Dialog.Draw(ImGuiWindowFlags overwriteFlags) in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/Dialogs/Dialog.cs:line 71
   at Hexa.NET.ImGui.Widgets.Dialogs.DialogManager.Draw() in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/Dialogs/DialogManager.cs:line 43
   at Hexa.NET.ImGui.Widgets.WidgetManager.Draw() in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/Hexa.NET.ImGui.Widgets/WidgetManager.cs:line 109
   at TestApp.Program.Render() in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/TestApp/Program.cs:line 88
   at TestApp.Program.Main(String[] args) in /Users/borislav/Projects/Hexa.NET.ImGui.Widgets/TestApp/Program.cs:line 71

<img width="1392" alt="Screenshot 2024-11-08 at 19 21 24" src="https://github.com/user-attachments/assets/367b2abc-da24-443e-b5ec-4828309a0957">

**Comment by JunaMeinhold** [comment]
That's probably just a missing try catch, should /dev even be visible?

**Comment by bparvanov** [comment]
Another crash happens when I expand the root folder, but this time at different place:
Assertion failed: (window->IDStack.Size > 1), function TreePop, file imgui_widgets.cpp, line 6791.

<img width="1440" alt="Screenshot 2024-11-09 at 9 08 26" src="https://github.com/user-attachments/assets/05134df0-1996-4841-a7ed-245cfc3ea0fe">

I added the Console.WriteLine on the screenshot to get some info and this prints out before the crash:

/Library
/Library/Apple
/Library/Apple/usr
/Library/Apple/usr/bin
/Library/Apple/usr/libexec
/Library/Apple/Library
/Library/Apple/Library/Bundles
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/_CodeSignature
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/de.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/he.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/en_AU.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/ar.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/el.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/ja.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/en.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/uk.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/es_419.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/zh_CN.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/es.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/pt_BR.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/da.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/it.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/sk.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/pt_PT.lproj
/Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/ms.lproj
Assertion failed: (window->IDStack.Size > 1), function TreePop, file imgui_widgets.cpp, line 6791.


And this is the whole content of /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/:

-rw-r--r--  1 root  wheel  12104 Aug  4 13:31 CompatibilityNotificationData.plist
-rw-r--r--  1 root  wheel   5270 Aug  4 13:31 Localizable.loctable
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 ar.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 ca.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 cs.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 da.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 de.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 el.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 en.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 en_AU.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 en_GB.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 es.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 es_419.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 fi.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 fr.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 fr_CA.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 he.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 hi.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 hr.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 hu.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 id.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 it.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 ja.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 ko.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 ms.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 nl.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 no.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 pl.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 pt_BR.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 pt_PT.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 ro.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 ru.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 sk.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 sv.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 th.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 tr.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 uk.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 vi.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 zh_CN.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 zh_HK.lproj
drwxr-xr-x  2 root  wheel     64 Aug  4 13:31 zh_TW.lproj

All .lproj folders are empty

**Comment by bparvanov** [comment]
> That's probably just a missing try catch, should /dev even be visible?

It's useless folder for a FilePicker, I think...

**Comment by JunaMeinhold** [comment]
it's even worse on linux
![image](https://github.com/user-attachments/assets/363bba69-1041-45fb-a6e4-c0e511308640)

**Comment by JunaMeinhold** [comment]
> Another crash happens when I expand the root folder, but this time at different place: Assertion failed: (window->IDStack.Size > 1), function TreePop, file imgui_widgets.cpp, line 6791.
> <img alt="Screenshot 2024-11-09 at 9 08 26" width="1440" src="https://private-user-images.githubusercontent.com/7011250/384585176-05134df0-1996-4841-a7ed-245cfc3ea0fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTEyNDYsIm5iZiI6MTczMTE1MDk0NiwicGF0aCI6Ii83MDExMjUwLzM4NDU4NTE3Ni0wNTEzNGRmMC0xOTk2LTQ4NDEtYTdlZC0yNDVjZmMzZWEwZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDlUMTExNTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFmNTdlZTNhNjE1N2RiYWM3NTk5MWMyZjliM2YwYTg1ZTIyM2NmNjc0N2NhZTRhMTQyOTY5ZWE1ZmZjMWY3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QJgw-QIA12wngdV9SHCYoJZatDvy6Nd24tfw82Rtp08">
> 
> I added the Console.WriteLine on the screenshot to get some info and this prints out before the crash:
> 
> /Library /Library/Apple /Library/Apple/usr /Library/Apple/usr/bin /Library/Apple/usr/libexec /Library/Apple/Library /Library/Apple/Library/Bundles /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/_CodeSignature /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/de.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/he.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/en_AU.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/ar.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/el.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/ja.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/en.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/uk.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/es_419.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/zh_CN.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/es.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/pt_BR.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/da.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/it.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/sk.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/pt_PT.lproj /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/ms.lproj Assertion failed: (window->IDStack.Size > 1), function TreePop, file imgui_widgets.cpp, line 6791.
> 
> And this is the whole content of /Library/Apple/Library/Bundles/CompatibilityNotificationData.bundle/Contents/Resources/:
> 
> -rw-r--r-- 1 root wheel 12104 Aug 4 13:31 CompatibilityNotificationData.plist -rw-r--r-- 1 root wheel 5270 Aug 4 13:31 Localizable.loctable drwxr-xr-x 2 root wheel 64 Aug 4 13:31 ar.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 ca.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 cs.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 da.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 de.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 el.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 en.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 en_AU.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 en_GB.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 es.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 es_419.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 fi.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 fr.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 fr_CA.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 he.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 hi.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 hr.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 hu.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 id.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 it.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 ja.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 ko.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 ms.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 nl.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 no.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 pl.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 pt_BR.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 pt_PT.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 ro.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 ru.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 sk.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 sv.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 th.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 tr.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 uk.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 vi.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 zh_CN.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 zh_HK.lproj drwxr-xr-x 2 root wheel 64 Aug 4 13:31 zh_TW.lproj
> 
> All .lproj folders are empty

that's a problem with the custom tree node, i simply switched to default one until i find a solution to fix it.

**Comment by JunaMeinhold** [comment]
I also see that the icons for Desktop Documents etc is missing. That's weird since i use the normal c# api for that

**Comment by JunaMeinhold** [comment]
I think i fixed it. (everything)

**Comment by bparvanov** [comment]
Now the app crashes immediately after I click on the Open File Dialog button..

<img width="1440" alt="Screenshot 2024-11-09 at 15 42 23" src="https://github.com/user-attachments/assets/cec14207-208e-4888-ab59-2a57e5f63a56">

It happens that the first folder in FileSystemHelper.SpecialDirs has empty Name and Path:

<img width="1440" alt="Screenshot 2024-11-09 at 15 40 13" src="https://github.com/user-attachments/assets/9e26069e-75eb-4b70-9d05-c19bc9439d27">

The special folders after the first one are ok (Downloads, Documents, Music, Pictures, Videos)

**Comment by bparvanov** [comment]
Ok, I found the reason:

https://github.com/dotnet/runtime/issues/100440#issuecomment-2028873985

<img width="827" alt="Screenshot 2024-11-09 at 16 13 13" src="https://github.com/user-attachments/assets/1ea469e7-2351-4dc3-bc5b-6253aad18a5e">

but probably it would be a good idea to check for a returned empty string from Environment.GetFolderPath(folder)

**Comment by bparvanov** [comment]
After I enabled access to the Desktop folder for Rider, now it looks good

<img width="1392" alt="Screenshot 2024-11-09 at 16 19 59" src="https://github.com/user-attachments/assets/7e60ab7b-f694-485e-992c-0fb66edf3da5">

**Comment by bparvanov** [comment]
Hmm wait... the subfolders don't appear below the root item in the tree control (because for some reason their Type is File)

**Comment by JunaMeinhold** [comment]
I fixed it, i will never trust ChatGPT again for struct layouts... (before you ask why i used ChatGPT, getting those headers isn't that easy)

![image](https://github.com/user-attachments/assets/d1a165b8-901b-4c19-88a6-d5d3512639d4)

**Comment by bparvanov** [comment]
It's fine now.. Thanks 🥇 

I use Anthropic's Claude (https://claude.ai/download)... They say it's better than ChatGPT for programming queries..
